name: Deploy to Cloudflare Pages

on:
  issue_comment:
    types: [created]

jobs: 
  preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.comment.body == 'preview' && github.event.issue.pull_request

    steps:
      - name: Comment on PR
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@0.9.0
        with: 
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Preview CI has started.'
              })

      - uses: actions/checkout@v4

      - name: Checkout PR
        if: github.event_name == 'issue_comment'
        run: gh pr checkout ${{ github.event.issue.number }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        